# Problem Number 12
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
 #1: 1
 #3: 1,3
 #......
 #28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?
import math

def num_div(triangle):
    div = 0
    for i in range(1, int(math.sqrt(triangle)) + 1):
        if triangle % i == 0: div += 1
    return div * 2

position = 2
triangle = 0

while True:
    for i in range(1, position):
        triangle += i
    if num_div(triangle) > 500: 
        break
    position += 1
    triangle = 0
    
print("Value of the First Triangle Number to have over Five Hundred Divisors: ", triangle)